# Generated by Django 3.1.5 on 2021-01-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210114_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='geofenceevent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='geofenceevent',
            name='user',
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='geofence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hello.geofence'),
        ),
    ]
