# Generated by Django 3.1.5 on 2021-01-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceevent',
            name='time',
            field=models.DateTimeField(verbose_name='recorded'),
        ),
    ]
